//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Logistics.Models
{
    using System;
    using System.Collections.Generic;

    public class T_Goods
    {
        [Key]
        public string BillID { get; set; }

        [Required]
        public string Password { get; set; }

        public int CustomerID { get; set; }
        public string SenderName { get; set; }
        public string SenderTel { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverTel { get; set; }
        public string ReceiverAddress { get; set; }
        public Nullable<int> GoodsType { get; set; }

        public string GoodsName { get; set; }
        //public Nullable<float> Volume { get; set; }
        //public Nullable<float> Weight { get; set; }

        public Nullable<float> Measure { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> PackingType { get; set; }
        public Nullable<int> Price { get; set; } //国际运费

        public Nullable<int> ChinaPrice { get; set; }
        public Nullable<int> PackingPrice { get; set; }
        public Nullable<int> InsurancePrice { get; set; }
        public Nullable<int> SumPrice { get; set; }
        public Nullable<int> RecorderID { get; set; }
        public Nullable<System.DateTime> RecordTime { get; set; }
        public Nullable<int> TransCompID { get; set; }

        public string TransCompName { get; set; }
        public string TransBill { get; set; }
        public Nullable<System.DateTime> TransTime { get; set; }
        public Nullable<int> TransRecoderID { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> PriceType { get; set; }

        public Nullable<int> UnitPrice { get; set; }
        public string Status { get; set; }
        public int PayType { get; set; }
        public string Remark { get; set; }

        public bool hasReceiveMoney { get; set; }
        public int MoneyReceiver { get; set; }

        public DateTime? MoneyReceiveTime { get; set; }

        public string MoneyRemark { get; set; }

        public int Seq { get; set; }

        public int BillFee { get; set; }

        public string IdCard
        {
            get; set;
        }

        public int CIQPrice
        {
            get;set;
        }

        public int TaxRate
        {
            get;set;
        }

        public int TaxPrice
        {
            get;set;
        }
    }
}
