//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Logistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GoodsTransDetail
    {
        [Key,Column(Order = 1)]
        public string BillID { get; set; }
        [Key,Column(Order = 2)]
        public string GoodsID { get; set; }
        public string GoodsStatu { get; set; }
        public Nullable<int> ReceiverID { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
    }
}
