//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Logistics.Models
{
    using System;
    using System.Collections.Generic;

    public partial class T_PriceInfo
    {
        [Key]
        public int PriceID { get; set; }

        public string PriceName { get; set; }
        public Nullable<int> UnitPrice { get; set; }

        public override string ToString()
        {
            return PriceName;
        }
    }
}
