//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Logistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TransCompany
    {
        [Key]
        [Required]
        [Display(Name = "公司编号")]
        public int TransCompanyID { get; set; }

        [Display(Name = "公司名称")]
        public string TransCompanyName { get; set; }

        [Display(Name = "公司代码")]
        public string TransCompanyCode { get; set; }

        public int BillLength { get; set; }

        public override string ToString()
        {
            return TransCompanyName;
        }
    }
}
