//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace Logistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Users
    {
        [Key]
        public int UserID { get; set; }
        public string UserName { get; set; }
        
        public string LoginName { get; set; }
        public string Password { get; set; }

        [DefaultValue("0")]
        public string Status { get; set; }

        public int StoreID { get; set; }

        public int RoleID { get; set; }
    }
}
